version: '2'
services:
  node:
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    networks:
      custom:
        ipv4_address: 172.0.0.4
    ports:
      - '3000:3000'
    command: 'node index.js'

  redis:
    image: 'redis'
    container_name: 'cache'
    networks:
      custom:
        ipv4_address: 172.0.0.3
    ports:
      - '6379:6379'

networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
